# Generated by Django 5.2.15 on 2026-06-13 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('github_verified', models.BooleanField(default=False)),
                ('github_join_date', models.DateTimeField(blank=True, null=True)),
                ('inner_self', models.TextField(blank=True, help_text="What's actually going on inside?")),
                ('struggles', models.TextField(blank=True, help_text="What's hard? What do you hide?")),
                ('crazy_interests', models.TextField(blank=True, help_text="What do you love that others don't get?")),
                ('what_i_hide', models.TextField(blank=True, help_text="What don't people know about you?")),
                ('looking_for', models.TextField(blank=True, help_text='What kind of human do you want to find?')),
                ('show_github_on_profile', models.BooleanField(default=False)),
                ('allow_anonymous_matching', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
